export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED = 'FAILED'

export const CREATE_POST_REQUESTED = 'CREATE_POST_REQUESTED'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED'

export const GET_USER_POSTS = 'GET_USER_POSTS'
export const GET_POSTS = 'GET_POSTS'

export const DELETE_POST_REQUESTED = 'DELETE_POST_REQUESTED'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED'

export const GET_POST_DETAILS_REQUESTED = 'GET_POST_DETAILS_REQUESTED'
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS'
export const GET_POST_DETAILS_FAILED = 'GET_POST_DETAILS_FAILED'

export const GET_POST_DETAILS = 'GET_POST_DETAILS'

export const UPDATE_POST_REQUESTED = 'UPDATE_POST_REQUESTED'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAILED = 'UPDATE_POST_FAILED'

export const LOGOUT = 'LOGOUT'