export const strings = {
  enter : 'Enter',
  titleText : 'Title*',
  titleHint : 'Title field cannot be empty',
  remunerationText : 'Remuneration',
  remunerationHint : 'e.g. $20 - $25 per hour',
  locationText : 'Location*',
  locationHint : 'Location field cannot be empty',
  workType : 'Work Type',
  fullTime : 'Full Time',
  partTime : 'Part Time',
  temporary : 'Temporary',
  casual : 'Casual',
  closingDate : 'Closing Date',
  landScape : 'landscape',
  descriptionText : 'Description',
  requiredSkillText : 'Required Skills',
  requiredSkillHint : 'Enter skill name and press Enter',
  howToApply : 'How to Apply*',
  howToApplyHint : 'How to Apply field cannot be empty',
  submit : 'Submit',
  update : 'Update',
}